include:
  - path: 'qbittorrent-pt/docker-compose.qbittorrent-pt.yml'
  - path: 'qbittorrent/docker-compose.qbittorrent.yml'
  - path: 'filebrowser/docker-compose.filebrowser.yml'
  - path: 'seafile/docker-compose.seafile.yml'
  - path: 'frps/docker-compose.frps.yml'
  - path: 'node-exporter/docker-compose.node-exporter.yml'