services:
  filebrowser:
    image: 'filebrowser/filebrowser:${FILEBROWSER_IMAGE_VERSION:-s6}'
    restart: unless-stopped
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'UID=${PUID:-1000}'
      - 'GID=${PGID:-100}'
      - 'PUID=${PUID:-1000}'
      - 'PGID=${PGID:-100}'
    ports:
      - '8083:80'
    volumes:
      - ${FILEBROWSER_VOLUME:-.}/conf:/config
      - ${FILEBROWSER_VOLUME:-.}/data:/database
      - ${TOWER_VOLUME:-/mnt/user}:/srv