services:
  qbittorrent-pt:
    image: 'linuxserver/qbittorrent:${QBITTORRENT_IMAGE_VERSION:-latest}'
    restart: always
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'PUID=${PUID:-1000}'
      - 'PGID=${PGID:-100}'
      - 'UMASK=${UMASK:-000}'
      - 'WEBUI_PORT=8081'
    network_mode: host
    volumes:
      - ${QBITTORRENT_PT_VOLUME:-.}/conf:/config
      - ${QBITTORRENT_PT_VOLUME:-.}/incomplete:/mnt/incomplete
      - ${MEDIA_VOLUME:-/mnt/user/media}:/mnt/user/media